// File generated by FlutterFire CLI.
// This is a placeholder. Replace with actual Firebase configuration.
// 
// To generate this file properly, run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// For now, using placeholder values that need to be replaced.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
        appId: '1:123456789:web:abcdef',
        messagingSenderId: '123456789',
        projectId: 'your-project-id',
        authDomain: 'your-project-id.firebaseapp.com',
        storageBucket: 'your-project-id.appspot.com',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:android:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:ios:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
          iosBundleId: 'com.example.parakeet',
        );
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:macos:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
          iosBundleId: 'com.example.parakeet',
        );
      case TargetPlatform.windows:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:windows:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
        );
      case TargetPlatform.linux:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:linux:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}

