// File generated by FlutterFire CLI.
// This is a placeholder. Replace with actual Firebase configuration.
// 
// To generate this file properly, run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// For now, using placeholder values that need to be replaced.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String apiKey = String.fromEnvironment(
    'FIREBASE_API_KEY',
    defaultValue: 'AIzaSyDummyKeyReplaceWithYourOwn',
  );
  static const String appId = String.fromEnvironment(
    'FIREBASE_APP_ID',
    defaultValue: '1:123456789:web:abcdef',
  );
  static const String messagingSenderId = String.fromEnvironment(
    'FIREBASE_MESSAGING_SENDER_ID',
    defaultValue: '123456789',
  );
  static const String projectId = String.fromEnvironment(
    'FIREBASE_PROJECT_ID',
    defaultValue: 'your-project-id',
  );
  static const String authDomain = String.fromEnvironment(
    'FIREBASE_AUTH_DOMAIN',
    defaultValue: 'your-project-id.firebaseapp.com',
  );
  static const String storageBucket = String.fromEnvironment(
    'FIREBASE_STORAGE_BUCKET',
    defaultValue: 'your-project-id.appspot.com',
  );

  /// True only after the placeholder Firebase web key has been replaced.
  static bool get isConfigured =>
      apiKey.isNotEmpty &&
      !apiKey.contains('Dummy') &&
      apiKey != 'YOUR_API_KEY' &&
      projectId != 'your-project-id' &&
      projectId != 'YOUR_PROJECT_ID';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: apiKey,
        appId: appId,
        messagingSenderId: messagingSenderId,
        projectId: projectId,
        authDomain: authDomain,
        storageBucket: storageBucket,
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:android:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:ios:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
          iosBundleId: 'com.example.parakeet',
        );
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:macos:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
          iosBundleId: 'com.example.parakeet',
        );
      case TargetPlatform.windows:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:windows:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
        );
      case TargetPlatform.linux:
        return const FirebaseOptions(
          apiKey: 'AIzaSyDummyKeyReplaceWithYourOwn',
          appId: '1:123456789:linux:abcdef',
          messagingSenderId: '123456789',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}

